/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/bode'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AdminIndexRouteImport } from './routes/bode/index'
import { Route as AdminBanksRouteImport } from './routes/bode/banks'
import { Route as AdminDepositsRouteImport } from './routes/bode/deposits'
import { Route as AdminLoginRouteImport } from './routes/bode/login'
import { Route as AdminNotificationsRouteImport } from './routes/bode/notifications'
import { Route as AdminQrRouteImport } from './routes/bode/qr'
import { Route as AdminReportsRouteImport } from './routes/bode/reports'
import { Route as AdminResultsRouteImport } from './routes/bode/results'
import { Route as AdminSettingsRouteImport } from './routes/bode/settings'
import { Route as AdminSupportRouteImport } from './routes/bode/support'
import { Route as AdminTradeRouteImport } from './routes/bode/trade'
import { Route as AdminUsersRouteImport } from './routes/bode/users'
import { Route as AdminVerifyRouteImport } from './routes/bode/verify'
import { Route as AdminWithdrawalsRouteImport } from './routes/bode/withdrawals'
import { Route as AdminUsersUserIdRouteImport } from './routes/bode/users.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/bode',
  path: '/bode',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBanksRoute = AdminBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQrRoute = AdminQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTradeRoute = AdminTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bode': typeof AdminRouteWithChildren
  '/deposit': typeof DepositRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/bode/banks': typeof AdminBanksRoute
  '/bode/deposits': typeof AdminDepositsRoute
  '/bode/login': typeof AdminLoginRoute
  '/bode/notifications': typeof AdminNotificationsRoute
  '/bode/qr': typeof AdminQrRoute
  '/bode/reports': typeof AdminReportsRoute
  '/bode/results': typeof AdminResultsRoute
  '/bode/settings': typeof AdminSettingsRoute
  '/bode/support': typeof AdminSupportRoute
  '/bode/trade': typeof AdminTradeRoute
  '/bode/users': typeof AdminUsersRouteWithChildren
  '/bode/verify': typeof AdminVerifyRoute
  '/bode/withdrawals': typeof AdminWithdrawalsRoute
  '/bode/': typeof AdminIndexRoute
  '/bode/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/deposit': typeof DepositRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/bode/banks': typeof AdminBanksRoute
  '/bode/deposits': typeof AdminDepositsRoute
  '/bode/login': typeof AdminLoginRoute
  '/bode/notifications': typeof AdminNotificationsRoute
  '/bode/qr': typeof AdminQrRoute
  '/bode/reports': typeof AdminReportsRoute
  '/bode/results': typeof AdminResultsRoute
  '/bode/settings': typeof AdminSettingsRoute
  '/bode/support': typeof AdminSupportRoute
  '/bode/trade': typeof AdminTradeRoute
  '/bode/users': typeof AdminUsersRouteWithChildren
  '/bode/verify': typeof AdminVerifyRoute
  '/bode/withdrawals': typeof AdminWithdrawalsRoute
  '/bode': typeof AdminIndexRoute
  '/bode/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bode': typeof AdminRouteWithChildren
  '/deposit': typeof DepositRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/bode/banks': typeof AdminBanksRoute
  '/bode/deposits': typeof AdminDepositsRoute
  '/bode/login': typeof AdminLoginRoute
  '/bode/notifications': typeof AdminNotificationsRoute
  '/bode/qr': typeof AdminQrRoute
  '/bode/reports': typeof AdminReportsRoute
  '/bode/results': typeof AdminResultsRoute
  '/bode/settings': typeof AdminSettingsRoute
  '/bode/support': typeof AdminSupportRoute
  '/bode/trade': typeof AdminTradeRoute
  '/bode/users': typeof AdminUsersRouteWithChildren
  '/bode/verify': typeof AdminVerifyRoute
  '/bode/withdrawals': typeof AdminWithdrawalsRoute
  '/bode/': typeof AdminIndexRoute
  '/bode/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bode'
    | '/deposit'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/trade'
    | '/wallet'
    | '/withdraw'
    | '/bode/banks'
    | '/bode/deposits'
    | '/bode/login'
    | '/bode/notifications'
    | '/bode/qr'
    | '/bode/reports'
    | '/bode/results'
    | '/bode/settings'
    | '/bode/support'
    | '/bode/trade'
    | '/bode/users'
    | '/bode/verify'
    | '/bode/withdrawals'
    | '/bode/'
    | '/bode/users/$userId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/deposit'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/trade'
    | '/wallet'
    | '/withdraw'
    | '/bode/banks'
    | '/bode/deposits'
    | '/bode/login'
    | '/bode/notifications'
    | '/bode/qr'
    | '/bode/reports'
    | '/bode/results'
    | '/bode/settings'
    | '/bode/support'
    | '/bode/trade'
    | '/bode/users'
    | '/bode/verify'
    | '/bode/withdrawals'
    | '/bode'
    | '/bode/users/$userId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bode'
    | '/deposit'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/trade'
    | '/wallet'
    | '/withdraw'
    | '/bode/banks'
    | '/bode/deposits'
    | '/bode/login'
    | '/bode/notifications'
    | '/bode/qr'
    | '/bode/reports'
    | '/bode/results'
    | '/bode/settings'
    | '/bode/support'
    | '/bode/trade'
    | '/bode/users'
    | '/bode/verify'
    | '/bode/withdrawals'
    | '/bode/'
    | '/bode/users/$userId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  DepositRoute: typeof DepositRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TradeRoute: typeof TradeRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bode': {
      id: '/bode'
      path: '/bode'
      fullPath: '/bode'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bode/': {
      id: '/bode/'
      path: '/'
      fullPath: '/bode/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/banks': {
      id: '/bode/banks'
      path: '/banks'
      fullPath: '/bode/banks'
      preLoaderRoute: typeof AdminBanksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/deposits': {
      id: '/bode/deposits'
      path: '/deposits'
      fullPath: '/bode/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/login': {
      id: '/bode/login'
      path: '/login'
      fullPath: '/bode/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/notifications': {
      id: '/bode/notifications'
      path: '/notifications'
      fullPath: '/bode/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/qr': {
      id: '/bode/qr'
      path: '/qr'
      fullPath: '/bode/qr'
      preLoaderRoute: typeof AdminQrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/reports': {
      id: '/bode/reports'
      path: '/reports'
      fullPath: '/bode/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/results': {
      id: '/bode/results'
      path: '/results'
      fullPath: '/bode/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/settings': {
      id: '/bode/settings'
      path: '/settings'
      fullPath: '/bode/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/support': {
      id: '/bode/support'
      path: '/support'
      fullPath: '/bode/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/trade': {
      id: '/bode/trade'
      path: '/trade'
      fullPath: '/bode/trade'
      preLoaderRoute: typeof AdminTradeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/users': {
      id: '/bode/users'
      path: '/users'
      fullPath: '/bode/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/verify': {
      id: '/bode/verify'
      path: '/verify'
      fullPath: '/bode/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/withdrawals': {
      id: '/bode/withdrawals'
      path: '/withdrawals'
      fullPath: '/bode/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bode/users/$userId': {
      id: '/bode/users/$userId'
      path: '/$userId'
      fullPath: '/bode/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminBanksRoute: typeof AdminBanksRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminQrRoute: typeof AdminQrRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTradeRoute: typeof AdminTradeRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminVerifyRoute: typeof AdminVerifyRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBanksRoute: AdminBanksRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminQrRoute: AdminQrRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTradeRoute: AdminTradeRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminVerifyRoute: AdminVerifyRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  DepositRoute: DepositRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TradeRoute: TradeRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
